// <auto-generated />
using System;
using GoodHamburger.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423040157_AjusteRelacaoMuitosParaMuitos")]
    partial class AjusteRelacaoMuitosParaMuitos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GoodHamburger.API.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "X Burger",
                            Preco = 5.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            Nome = "X Egg",
                            Preco = 4.50m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "X Bacon",
                            Preco = 7.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Batata Frita",
                            Preco = 2.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Coca-Cola 250ml",
                            Preco = 2.50m,
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("GoodHamburger.API.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ItemPedido", b =>
                {
                    b.Property<int>("ItensId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItensId", "PedidosId");

                    b.HasIndex("PedidosId");

                    b.ToTable("PedidoItens", (string)null);
                });

            modelBuilder.Entity("ItemPedido", b =>
                {
                    b.HasOne("GoodHamburger.API.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodHamburger.API.Models.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
